# Generated by Django 5.1.6 on 2025-03-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['content_type', 'level', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When active, this category appears in menus'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default category for uncategorized content'),
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Content Type (Top Level)'), (2, 'Parent Category'), (3, 'Subcategory')], default=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='content_type',
            field=models.CharField(choices=[('NEWS_STORIES', 'News Stories'), ('NEWS_BULLETINS', 'News Bulletins'), ('SPORT', 'Sport'), ('FINANCE', 'Finance'), ('SPECIALTY', 'Specialty')], default='News Stories', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('content_type', 'is_default'), name='unique_default_category_per_type'),
        ),
    ]
