# Generated by Django 5.1.6 on 2025-03-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0002_alter_category_options_category_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='translated_from',
        ),
        migrations.AlterField(
            model_name='story',
            name='is_translation',
            field=models.BooleanField(default=False, help_text='Whether this story is a translation of another story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
