# Generated by Django 5.1.6 on 2025-05-14 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0005_storyactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='The journalist assigned to review this story', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='translation_of',
            field=models.ForeignKey(blank=True, help_text='The original story this is a translation of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='newsroom.story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'In Review'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('TRANSLATED', 'Translated'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
