# Generated by Django 5.1.6 on 2025-05-15 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0006_story_reviewer_story_translation_of_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('AFRIKAANS', 'Afrikaans'), ('ZULU', 'Zulu'), ('XHOSA', 'Xhosa'), ('SESOTHO', 'Sesotho'), ('SETSWANA', 'Setswana'), ('TSHIVENDA', 'Tshivenda'), ('XITSONGA', 'Xitsonga'), ('SISWATI', 'Siswati'), ('ISINDEBELE', 'IsiNdebele')], default='ENGLISH', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='religion_classification',
            field=models.CharField(choices=[('GENERAL', 'General'), ('CHRISTIAN', 'Christian'), ('ISLAMIC', 'Islamic'), ('HINDU', 'Hindu'), ('BUDDHIST', 'Buddhist'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='The journalist assigned to review this story', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'In Review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='newsroom.story'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('WRITE', 'Write Story'), ('EDIT', 'Edit Story'), ('REVIEW', 'Review Story'), ('TRANSLATE', 'Translate Story'), ('RECORD', 'Record Audio'), ('OTHER', 'Other')], default='WRITE', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('WRITE', 'Write Story'), ('EDIT', 'Edit Story'), ('REVIEW', 'Review Story'), ('TRANSLATE', 'Translate Story'), ('RECORD', 'Record Audio'), ('OTHER', 'Other')], default='WRITE', max_length=20),
        ),
    ]
