[build]
builder = "nixpacks"
buildCommand = "python manage.py tailwind build && python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn newskoop.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"