# Generated by Django 5.1.6 on 2025-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_primary_contact',
            field=models.BooleanField(default=False, help_text='Designates whether this user is the primary contact for a radio station.'),
        ),
    ]
